### ISSUE TITLE
Hepatocyte clearance negative

### ISSUE THREAD

**Issue by ReneGeci** [swansonk14/admet_ai#1]
Hello, for some compounds your tool predicts negative hepatocyte clearance values. From a practical standpoint that doesnt make much sense. So, should I just interpret these as 0 values (i.e. no clearance)?

**Comment by swansonk14** [comment]
Hi @ReneGeci,

Thank you for bringing up this issue! You're right that some of these values do not make practical sense. This happens because on regression datasets, the underlying machine learning model is trained with a linear activation as the final activation, meaning any number between -infinity and infinity can be predicted. The model should learn to predict the correct range, but on some of the smaller and noisier datasets such as hepatocyte clearance, this doesn't always happen.

I've now modified the website code so that it clips values to a feasible range (e.g., >0 for hepatocyte clearance). If you download the predictions file, you'll still get the original raw prediction, which might be negative, but this way the website will show only feasible values. This change has been made here on GitHub and is available in ADMET-AI version 1.3.0, and I will push the change to the live website (https://admet.ai.greenstonebio.com/) soon.

Best,
Kyle
