### ISSUE TITLE
hERG dataset

### ISSUE THREAD

**Issue by raweru** [swansonk14/admet_ai#12]
Hi 

Which tdc hERG dataset was the model trained on? I see there is a couple in the tdc website https://tdcommons.ai/single_pred_tasks/tox/#herg-blockers. Is the model only trained on herg-blockers? Because that has quite a low mol count of 648 whereas the hERG_central has over 300k. 

Im only wondering as I tried the model on some compounds we tested experimentally and they got a high score while we know they dont block.

**Comment by swansonk14** [comment]
Hi @raweru,

Thank you for your question! We did train on the hERG blockers dataset, which is unfortunately very small. While we would have liked to train on more data, we chose to use this dataset for two reasons: (1) it is part of the TDC ADMET benchmark [leaderboard](https://tdcommons.ai/benchmark/admet_group/overview/), which we wanted to use to compare ADMET-AI with other ADMET models, and (2) doing multitask training on all the ADMET datasets with the 300k hERG dataset empirically led to poor results, perhaps because the size of the hERG dataset overwhelms the other ADMET datasets. However, if you would like to build a hERG model using a larger dataset like hERG central, you should be able to follow our [docs](https://github.com/swansonk14/admet_ai/blob/main/docs/reproduce.md) with slight modifications to include the hERG dataset of your choice.

Please let me know if you have any additional questions!

Best,
Kyle
