### ISSUE TITLE
How to bypass max 1000 molecules on local install

### ISSUE THREAD

**Issue by Evert-Homan** [swansonk14/admet_ai#6]
Hi Kyle,

Sorry to bother you again, but on my local installation the maximum number of molecules to predict in one run is set to 1000. How can I increase this number? Where is this limit defined?

Also, it would be very useful if one could include an ID column in a csv file to identify molecules in the results. Now you have rely on the smiles only as it seems (?)

Thanks/Evert

**Comment by swansonk14** [comment]
Hi Evert,

Thanks for the questions!

For the number of molecules, that's set by the `max_molecules` parameter here: https://github.com/swansonk14/admet_ai/blob/main/admet_ai/web/run.py#L22. You can add `--max_molecules <n>` on the command line when running `admet_web`.

If you want to make a large number of ADMET predictions, I would recommend using the command line tool rather than the website. You can see an example of how to run it here: https://github.com/swansonk14/admet_ai/tree/main?tab=readme-ov-file#command-line-tool. I find it easier to manage long running experiments on the command line rather than via the website, which is more prone to crashing due to timeouts.

For the ID column, that's a good idea! I'll look into implementing that and I'll get back to you.

Best,
Kyle

**Comment by Evert-Homan** [comment]
Your quick replies are much appreciated. This is a perfectly acceptable solution, so I close this (non)-iisue.

BW/Evert
